
package DAOs.JuniperAPIDAOs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AvailTransactions", targetNamespace = "http://www.juniper.es/webservice/2007/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AvailTransactions {


    /**
     * Availability for hotels.
     * 
     * @param hotelAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "HotelAvail", action = "http://www.juniper.es/webservice/2007/HotelAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelAvail")
    @ResponseWrapper(localName = "HotelAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelAvailResponse")
    public JPAvailResponseRS hotelAvail(
        @WebParam(name = "HotelAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelAvail hotelAvailRQ);

    /**
     * Availability for rentacar.
     * 
     * @param rentacarAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "RentacarAvail", action = "http://www.juniper.es/webservice/2007/RentacarAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarAvail")
    @ResponseWrapper(localName = "RentacarAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarAvailResponse")
    public JPAvailResponseRS rentacarAvail(
        @WebParam(name = "RentacarAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarAvail rentacarAvailRQ);

    /**
     * Availability calendar for hotels.
     * 
     * @param hotelAvailCalendarRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "HotelAvailCalendar", action = "http://www.juniper.es/webservice/2007/HotelAvailCalendar")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelAvailCalendar", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelAvailCalendar")
    @ResponseWrapper(localName = "HotelAvailCalendarResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelAvailCalendarResponse")
    public JPAvailResponseRS hotelAvailCalendar(
        @WebParam(name = "HotelAvailCalendarRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelAvailCalendar hotelAvailCalendarRQ);

    /**
     * Future rates for hotels.
     * 
     * @param hotelFutureRatesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "HotelFutureRates", action = "http://www.juniper.es/webservice/2007/HotelFutureRates")
    @WebResult(name = "FutureRatesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelFutureRates", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelFutureRates")
    @ResponseWrapper(localName = "HotelFutureRatesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelFutureRatesResponse")
    public JPAvailResponseRS hotelFutureRates(
        @WebParam(name = "HotelFutureRatesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelFutureRates hotelFutureRatesRQ);

    /**
     * Availability for packages.
     * 
     * @param packageAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "PackageAvail", action = "http://www.juniper.es/webservice/2007/PackageAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageAvail")
    @ResponseWrapper(localName = "PackageAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageAvailResponse")
    public JPAvailResponseRS packageAvail(
        @WebParam(name = "PackageAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageAvailabilityRQ packageAvailRQ);

    /**
     * Change product for packages.
     * 
     * @param packageChangeProductRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "PackageChangeProduct", action = "http://www.juniper.es/webservice/2007/PackageChangeProduct")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageChangeProduct", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageChangeProduct")
    @ResponseWrapper(localName = "PackageChangeProductResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageChangeProductResponse")
    public JPAvailResponseRS packageChangeProduct(
        @WebParam(name = "PackageChangeProductRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageChangeProductRQ packageChangeProductRQ);

    /**
     * Availability for Flights.
     * 
     * @param flightAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "FlightAvail", action = "http://www.juniper.es/webservice/2007/FlightAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FlightAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightAvail")
    @ResponseWrapper(localName = "FlightAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightAvailResponse")
    public JPAvailResponseRS flightAvail(
        @WebParam(name = "FlightAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFlightAvail flightAvailRQ);

    /**
     * Pre-Availability for cruises.
     * 
     * @param cruisePreAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "CruisePreAvail", action = "http://www.juniper.es/webservice/2007/CruisePreAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruisePreAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruisePreAvail")
    @ResponseWrapper(localName = "CruisePreAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruisePreAvailResponse")
    public JPAvailResponseRS cruisePreAvail(
        @WebParam(name = "CruisePreAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruisePreAvail cruisePreAvailRQ);

    /**
     * Availability for cruises.
     * 
     * @param cruiseAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "CruiseAvail", action = "http://www.juniper.es/webservice/2007/CruiseAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseAvail")
    @ResponseWrapper(localName = "CruiseAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseAvailResponse")
    public JPAvailResponseRS cruiseAvail(
        @WebParam(name = "CruiseAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseAvail cruiseAvailRQ);

    /**
     * Availability for insurances.
     * 
     * @param insuranceAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "InsuranceAvail", action = "http://www.juniper.es/webservice/2007/InsuranceAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "InsuranceAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceAvail")
    @ResponseWrapper(localName = "InsuranceAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceAvailResponse")
    public JPAvailResponseRS insuranceAvail(
        @WebParam(name = "InsuranceAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPInsuranceAvail insuranceAvailRQ);

    /**
     * Availability for services.
     * 
     * @param serviceAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "ServiceAvail", action = "http://www.juniper.es/webservice/2007/ServiceAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServiceAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceAvail")
    @ResponseWrapper(localName = "ServiceAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceAvailResponse")
    public JPAvailResponseRS serviceAvail(
        @WebParam(name = "ServiceAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServiceAvailabilityRQ serviceAvailRQ);

    /**
     * Availability for transfers.
     * 
     * @param transferAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "TransferAvail", action = "http://www.juniper.es/webservice/2007/TransferAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferAvail")
    @ResponseWrapper(localName = "TransferAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferAvailResponse")
    public JPAvailResponseRS transferAvail(
        @WebParam(name = "TransferAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferAvailabilityRQ transferAvailRQ);

    /**
     * Availability for transfers.
     * 
     * @param transferAvailRQByHotel
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "TransferAvailByHotel", action = "http://www.juniper.es/webservice/2007/TransferAvailByHotel")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferAvailByHotel", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferAvailByHotel")
    @ResponseWrapper(localName = "TransferAvailByHotelResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferAvailByHotelResponse")
    public JPAvailResponseRS transferAvailByHotel(
        @WebParam(name = "TransferAvailRQByHotel", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferAvailabilityRQByHotel transferAvailRQByHotel);

    /**
     * Availability for visas.
     * 
     * @param visaAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPAvailResponseRS
     */
    @WebMethod(operationName = "VisaAvail", action = "http://www.juniper.es/webservice/2007/VisaAvail")
    @WebResult(name = "AvailabilityRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaAvail")
    @ResponseWrapper(localName = "VisaAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaAvailResponse")
    public JPAvailResponseRS visaAvail(
        @WebParam(name = "VisaAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaAvailabilityRQ visaAvailRQ);

}
