
package DAOs.SunHotelsAPIDAOs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NonStaticXMLAPI", targetNamespace = "http://xml.sunhotels.net/15/", wsdlLocation = "http://xml.sunhotels.net/15/PostGet/NonStaticXMLAPI.asmx?WSDL")
public class NonStaticXMLAPI
    extends Service
{

    private final static URL NONSTATICXMLAPI_WSDL_LOCATION;
    private final static WebServiceException NONSTATICXMLAPI_EXCEPTION;
    private final static QName NONSTATICXMLAPI_QNAME = new QName("http://xml.sunhotels.net/15/", "NonStaticXMLAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://xml.sunhotels.net/15/PostGet/NonStaticXMLAPI.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NONSTATICXMLAPI_WSDL_LOCATION = url;
        NONSTATICXMLAPI_EXCEPTION = e;
    }

    public NonStaticXMLAPI() {
        super(__getWsdlLocation(), NONSTATICXMLAPI_QNAME);
    }

    public NonStaticXMLAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), NONSTATICXMLAPI_QNAME, features);
    }

    public NonStaticXMLAPI(URL wsdlLocation) {
        super(wsdlLocation, NONSTATICXMLAPI_QNAME);
    }

    public NonStaticXMLAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NONSTATICXMLAPI_QNAME, features);
    }

    public NonStaticXMLAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NonStaticXMLAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NonStaticXMLAPISoap
     */
    @WebEndpoint(name = "NonStaticXMLAPISoap")
    public NonStaticXMLAPISoap getNonStaticXMLAPISoap() {
        return super.getPort(new QName("http://xml.sunhotels.net/15/", "NonStaticXMLAPISoap"), NonStaticXMLAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NonStaticXMLAPISoap
     */
    @WebEndpoint(name = "NonStaticXMLAPISoap")
    public NonStaticXMLAPISoap getNonStaticXMLAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.sunhotels.net/15/", "NonStaticXMLAPISoap"), NonStaticXMLAPISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NONSTATICXMLAPI_EXCEPTION!= null) {
            throw NONSTATICXMLAPI_EXCEPTION;
        }
        return NONSTATICXMLAPI_WSDL_LOCATION;
    }

}
