
package DAOs.JuniperAPIDAOs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookTransactions", targetNamespace = "http://www.juniper.es/webservice/2007/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookTransactions {


    /**
     * Fields Check payment.
     * 
     * @param checkPaymentRequiredFieldsRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckPaymentRequiredFieldsRS
     */
    @WebMethod(operationName = "CheckPaymentRequiredField", action = "http://www.juniper.es/webservice/2007/CheckPaymentRequiredField")
    @WebResult(name = "CheckPaymentRequiredFieldsRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CheckPaymentRequiredField", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CheckPaymentRequiredField")
    @ResponseWrapper(localName = "CheckPaymentRequiredFieldResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CheckPaymentRequiredFieldResponse")
    public JPCheckPaymentRequiredFieldsRS checkPaymentRequiredField(
        @WebParam(name = "CheckPaymentRequiredFieldsRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCheckPaymentRequiredFieldsRQ checkPaymentRequiredFieldsRQ);

    /**
     * Check payment
     * 
     * @param checkPaymentRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckPaymentRS
     */
    @WebMethod(operationName = "CheckPayment", action = "http://www.juniper.es/webservice/2007/CheckPayment")
    @WebResult(name = "CheckPaymentRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CheckPayment", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CheckPayment")
    @ResponseWrapper(localName = "CheckPaymentResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CheckPaymentResponse")
    public JPCheckPaymentRS checkPayment(
        @WebParam(name = "CheckPaymentRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCheckPaymentRQ checkPaymentRQ);

    /**
     * Credit Card payment.
     * 
     * @param paymentRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPPaymentRS
     */
    @WebMethod(operationName = "PaymentBooking", action = "http://www.juniper.es/webservice/2007/PaymentBooking")
    @WebResult(name = "PaymentRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PaymentBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PaymentBooking")
    @ResponseWrapper(localName = "PaymentBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PaymentBookingResponse")
    public JPPaymentRS paymentBooking(
        @WebParam(name = "PaymentRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPaymentRQ paymentRQ);

    /**
     * Get stored booking pricing.
     * 
     * @param shoppingBasketReadRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPShoppingBasketResult
     */
    @WebMethod(operationName = "ShoppingBasketRead", action = "http://www.juniper.es/webservice/2007/ShoppingBasketRead")
    @WebResult(name = "ShoppingBasketReadRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ShoppingBasketRead", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ShoppingBasketRead")
    @ResponseWrapper(localName = "ShoppingBasketReadResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ShoppingBasketReadResponse")
    public JPShoppingBasketResult shoppingBasketRead(
        @WebParam(name = "ShoppingBasketReadRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPShoppingBasketRead shoppingBasketReadRQ);

    /**
     * Store booking pricing.
     * 
     * @param shoppingBasketSaveRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPShoppingBasketResult
     */
    @WebMethod(operationName = "ShoppingBasketSave", action = "http://www.juniper.es/webservice/2007/ShoppingBasketSave")
    @WebResult(name = "ShoppingBasketSaveRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ShoppingBasketSave", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ShoppingBasketSave")
    @ResponseWrapper(localName = "ShoppingBasketSaveResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ShoppingBasketSaveResponse")
    public JPShoppingBasketResult shoppingBasketSave(
        @WebParam(name = "ShoppingBasketSaveRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPShoppingBasketSave shoppingBasketSaveRQ);

    /**
     * Booking for hotels.
     * 
     * @param hotelBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "HotelBooking", action = "http://www.juniper.es/webservice/2007/HotelBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelBooking")
    @ResponseWrapper(localName = "HotelBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelBookingResponse")
    public JPBookingRS hotelBooking(
        @WebParam(name = "HotelBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelBooking hotelBookingRQ);

    /**
     * book for rentacar.
     * 
     * @param rentacarBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "RentacarBooking", action = "http://www.juniper.es/webservice/2007/RentacarBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarBooking")
    @ResponseWrapper(localName = "RentacarBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarBookingResponse")
    public JPBookingRS rentacarBooking(
        @WebParam(name = "RentacarBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarBooking rentacarBookingRQ);

    /**
     * Booking for hotels.
     * 
     * @param insuranceBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "InsuranceBooking", action = "http://www.juniper.es/webservice/2007/InsuranceBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "InsuranceBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceBooking")
    @ResponseWrapper(localName = "InsuranceBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceBookingResponse")
    public JPBookingRS insuranceBooking(
        @WebParam(name = "InsuranceBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPInsuranceBooking insuranceBookingRQ);

    /**
     * Booking for packages.
     * 
     * @param packageBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "PackageBooking", action = "http://www.juniper.es/webservice/2007/PackageBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageBooking")
    @ResponseWrapper(localName = "PackageBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageBookingResponse")
    public JPBookingRS packageBooking(
        @WebParam(name = "PackageBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageBooking packageBookingRQ);

    /**
     * Booking for flights.
     * 
     * @param flightBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "FlightBooking", action = "http://www.juniper.es/webservice/2007/FlightBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FlightBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightBooking")
    @ResponseWrapper(localName = "FlightBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightBookingResponse")
    public JPBookingRS flightBooking(
        @WebParam(name = "FlightBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFlightBooking flightBookingRQ);

    /**
     * Booking for cruises.
     * 
     * @param cruiseBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "CruiseBooking", action = "http://www.juniper.es/webservice/2007/CruiseBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseBooking")
    @ResponseWrapper(localName = "CruiseBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseBookingResponse")
    public JPBookingRS cruiseBooking(
        @WebParam(name = "CruiseBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseBooking cruiseBookingRQ);

    /**
     * Booking for services.
     * 
     * @param serviceBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "ServiceBooking", action = "http://www.juniper.es/webservice/2007/ServiceBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServiceBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceBooking")
    @ResponseWrapper(localName = "ServiceBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceBookingResponse")
    public JPBookingRS serviceBooking(
        @WebParam(name = "ServiceBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServiceBooking serviceBookingRQ);

    /**
     * Booking for transfers.
     * 
     * @param transferBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "TransferBooking", action = "http://www.juniper.es/webservice/2007/TransferBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferBooking")
    @ResponseWrapper(localName = "TransferBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferBookingResponse")
    public JPBookingRS transferBooking(
        @WebParam(name = "TransferBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferBooking transferBookingRQ);

    /**
     * Booking for visa.
     * 
     * @param visaBookingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "VisaBooking", action = "http://www.juniper.es/webservice/2007/VisaBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaBooking")
    @ResponseWrapper(localName = "VisaBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaBookingResponse")
    public JPBookingRS visaBooking(
        @WebParam(name = "VisaBookingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaBooking visaBookingRQ);

    /**
     * Ticketing for flights.
     * 
     * @param flightTicketingRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPFlightTicketingRS
     */
    @WebMethod(operationName = "FlightTicketing", action = "http://www.juniper.es/webservice/2007/FlightTicketing")
    @WebResult(name = "FlightTicketingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FlightTicketing", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightTicketing")
    @ResponseWrapper(localName = "FlightTicketingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightTicketingResponse")
    public JPFlightTicketingRS flightTicketing(
        @WebParam(name = "FlightTicketingRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFlightTicketingRQ flightTicketingRQ);

    /**
     * cancel process for bookings.
     * 
     * @param cancelRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "CancelBooking", action = "http://www.juniper.es/webservice/2007/CancelBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CancelBookingResponse")
    public JPBookingRS cancelBooking(
        @WebParam(name = "CancelRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCancelRQ cancelRQ);

    /**
     * Read process for bookings.
     * 
     * @param readRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "ReadBooking", action = "http://www.juniper.es/webservice/2007/ReadBooking")
    @WebResult(name = "BookingRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ReadBooking", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ReadBooking")
    @ResponseWrapper(localName = "ReadBookingResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ReadBookingResponse")
    public JPBookingRS readBooking(
        @WebParam(name = "ReadRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPReadRQ readRQ);

    /**
     * Read process for Bookings Agency.
     * 
     * @param bookingListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingListRS
     */
    @WebMethod(operationName = "BookingList", action = "http://www.juniper.es/webservice/2007/BookingList")
    @WebResult(name = "BookingListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "BookingList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.BookingList")
    @ResponseWrapper(localName = "BookingListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.BookingListResponse")
    public JPBookingListRS bookingList(
        @WebParam(name = "BookingListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPBookingListRQ bookingListRQ);

    /**
     * Save final customer.
     * 
     * @param finalCustomerSaveRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPFinalCustomerSaveResult
     */
    @WebMethod(operationName = "FinalCustomerSave", action = "http://www.juniper.es/webservice/2007/FinalCustomerSave")
    @WebResult(name = "FinalCustomerSaveRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FinalCustomerSave", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FinalCustomerSave")
    @ResponseWrapper(localName = "FinalCustomerSaveResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FinalCustomerSaveResponse")
    public JPFinalCustomerSaveResult finalCustomerSave(
        @WebParam(name = "FinalCustomerSaveRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFinalCustomerSave finalCustomerSaveRQ);

    /**
     * Modify for hotels
     * 
     * @param hotelModifyRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPModifyRS
     */
    @WebMethod(operationName = "HotelModify", action = "http://www.juniper.es/webservice/2007/HotelModify")
    @WebResult(name = "ModifyRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelModify", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelModify")
    @ResponseWrapper(localName = "HotelModifyResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelModifyResponse")
    public JPModifyRS hotelModify(
        @WebParam(name = "HotelModifyRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelModify hotelModifyRQ);

    /**
     * ConfirmModify for hotels
     * 
     * @param hotelConfirmModifyRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRS
     */
    @WebMethod(operationName = "HotelConfirmModify", action = "http://www.juniper.es/webservice/2007/HotelConfirmModify")
    @WebResult(name = "ConfirmModifyRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelConfirmModify", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelConfirmModify")
    @ResponseWrapper(localName = "HotelConfirmModifyResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelConfirmModifyResponse")
    public JPBookingRS hotelConfirmModify(
        @WebParam(name = "HotelConfirmModifyRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelConfirmModify hotelConfirmModifyRQ);

}
