
package DAOs.JuniperAPIDAOs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckTransactions", targetNamespace = "http://www.juniper.es/webservice/2007/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckTransactions {


    /**
     * CheckAvail for hotels.
     * 
     * @param hotelCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "HotelCheckAvail", action = "http://www.juniper.es/webservice/2007/HotelCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelCheckAvail")
    @ResponseWrapper(localName = "HotelCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelCheckAvailResponse")
    public JPCheckAvailRS hotelCheckAvail(
        @WebParam(name = "HotelCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelCheckAvail hotelCheckAvailRQ);

    /**
     * CheckAvail for rentacar.
     * 
     * @param rentacarCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "RentacarCheckAvail", action = "http://www.juniper.es/webservice/2007/RentacarCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarCheckAvail")
    @ResponseWrapper(localName = "RentacarCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarCheckAvailResponse")
    public JPCheckAvailRS rentacarCheckAvail(
        @WebParam(name = "RentacarCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarCheckAvailRQ rentacarCheckAvailRQ);

    /**
     * CheckAvail for insurances.
     * 
     * @param insuranceCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "InsuranceCheckAvail", action = "http://www.juniper.es/webservice/2007/InsuranceCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "InsuranceCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceCheckAvail")
    @ResponseWrapper(localName = "InsuranceCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceCheckAvailResponse")
    public JPCheckAvailRS insuranceCheckAvail(
        @WebParam(name = "InsuranceCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPInsuranceCheckAvail insuranceCheckAvailRQ);

    /**
     * CheckAvail for packages.
     * 
     * @param packageCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "PackageCheckAvail", action = "http://www.juniper.es/webservice/2007/PackageCheckAvail")
    @WebResult(name = "PackageCheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageCheckAvail")
    @ResponseWrapper(localName = "PackageCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageCheckAvailResponse")
    public JPCheckAvailRS packageCheckAvail(
        @WebParam(name = "PackageCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageCheckAvailRQ packageCheckAvailRQ);

    /**
     * CheckAvail for Flights.
     * 
     * @param flightCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "FlightCheckAvail", action = "http://www.juniper.es/webservice/2007/FlightCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FlightCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightCheckAvail")
    @ResponseWrapper(localName = "FlightCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightCheckAvailResponse")
    public JPCheckAvailRS flightCheckAvail(
        @WebParam(name = "FlightCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFlightCheckAvailRQ flightCheckAvailRQ);

    /**
     * CheckAvail for cruises.
     * 
     * @param cruiseCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "CruiseCheckAvail", action = "http://www.juniper.es/webservice/2007/CruiseCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseCheckAvail")
    @ResponseWrapper(localName = "CruiseCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseCheckAvailResponse")
    public JPCheckAvailRS cruiseCheckAvail(
        @WebParam(name = "CruiseCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseCheckAvail cruiseCheckAvailRQ);

    /**
     * CheckAvail for services and tickets.
     * 
     * @param serviceCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "ServiceCheckAvail", action = "http://www.juniper.es/webservice/2007/ServiceCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServiceCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceCheckAvail")
    @ResponseWrapper(localName = "ServiceCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceCheckAvailResponse")
    public JPCheckAvailRS serviceCheckAvail(
        @WebParam(name = "ServiceCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServiceCheckAvailRQ serviceCheckAvailRQ);

    /**
     * CheckAvail for transfers.
     * 
     * @param transferCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "TransferCheckAvail", action = "http://www.juniper.es/webservice/2007/TransferCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferCheckAvail")
    @ResponseWrapper(localName = "TransferCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferCheckAvailResponse")
    public JPCheckAvailRS transferCheckAvail(
        @WebParam(name = "TransferCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferCheckAvailRQ transferCheckAvailRQ);

    /**
     * CheckAvail for visas services.
     * 
     * @param visaCheckAvailRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPCheckAvailRS
     */
    @WebMethod(operationName = "VisaCheckAvail", action = "http://www.juniper.es/webservice/2007/VisaCheckAvail")
    @WebResult(name = "CheckAvailRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaCheckAvail", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaCheckAvail")
    @ResponseWrapper(localName = "VisaCheckAvailResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaCheckAvailResponse")
    public JPCheckAvailRS visaCheckAvail(
        @WebParam(name = "VisaCheckAvailRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaCheckAvailRQ visaCheckAvailRQ);

    /**
     * BookingRules Of Hotels
     * 
     * @param hotelBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "HotelBookingRules", action = "http://www.juniper.es/webservice/2007/HotelBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelBookingRules")
    @ResponseWrapper(localName = "HotelBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelBookingRulesResponse")
    public JPBookingRulesRS hotelBookingRules(
        @WebParam(name = "HotelBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelBookingRuleRQ hotelBookingRulesRQ);

    /**
     * BookingRules Of Rentacar
     * 
     * @param rentacarBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "RentacarBookingRules", action = "http://www.juniper.es/webservice/2007/RentacarBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarBookingRules")
    @ResponseWrapper(localName = "RentacarBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarBookingRulesResponse")
    public JPBookingRulesRS rentacarBookingRules(
        @WebParam(name = "RentacarBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarBookingRulesRQ rentacarBookingRulesRQ);

    /**
     * BookingRules Of Flights
     * 
     * @param flightBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "FlightBookingRules", action = "http://www.juniper.es/webservice/2007/FlightBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FlightBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightBookingRules")
    @ResponseWrapper(localName = "FlightBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FlightBookingRulesResponse")
    public JPBookingRulesRS flightBookingRules(
        @WebParam(name = "FlightBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFlightBookingRulesRQ flightBookingRulesRQ);

    /**
     * BookingRules Of Insurances
     * 
     * @param insuranceBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "InsuranceBookingRules", action = "http://www.juniper.es/webservice/2007/InsuranceBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "InsuranceBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceBookingRules")
    @ResponseWrapper(localName = "InsuranceBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.InsuranceBookingRulesResponse")
    public JPBookingRulesRS insuranceBookingRules(
        @WebParam(name = "InsuranceBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPInsuranceBookingRulesRQ insuranceBookingRulesRQ);

    /**
     * BookingRules Of Packages
     * 
     * @param packageBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "PackageBookingRules", action = "http://www.juniper.es/webservice/2007/PackageBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageBookingRules")
    @ResponseWrapper(localName = "PackageBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageBookingRulesResponse")
    public JPBookingRulesRS packageBookingRules(
        @WebParam(name = "PackageBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageBookingRulesRQ packageBookingRulesRQ);

    /**
     * BookingRules of cruises.
     * 
     * @param cruiseBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "CruiseBookingRules", action = "http://www.juniper.es/webservice/2007/CruiseBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseBookingRules")
    @ResponseWrapper(localName = "CruiseBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseBookingRulesResponse")
    public JPBookingRulesRS cruiseBookingRules(
        @WebParam(name = "CruiseBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseBookingRulesRQ cruiseBookingRulesRQ);

    /**
     * BookingRules Of services
     * 
     * @param serviceBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "ServiceBookingRules", action = "http://www.juniper.es/webservice/2007/ServiceBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServiceBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceBookingRules")
    @ResponseWrapper(localName = "ServiceBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceBookingRulesResponse")
    public JPBookingRulesRS serviceBookingRules(
        @WebParam(name = "ServiceBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServiceBookingRulesRQ serviceBookingRulesRQ);

    /**
     * BookingRules Of transfers
     * 
     * @param transferBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "TransferBookingRules", action = "http://www.juniper.es/webservice/2007/TransferBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferBookingRules")
    @ResponseWrapper(localName = "TransferBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferBookingRulesResponse")
    public JPBookingRulesRS transferBookingRules(
        @WebParam(name = "TransferBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferBookingRulesRQ transferBookingRulesRQ);

    /**
     * BookingRules Of visas
     * 
     * @param visaBookingRulesRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPBookingRulesRS
     */
    @WebMethod(operationName = "VisaBookingRules", action = "http://www.juniper.es/webservice/2007/VisaBookingRules")
    @WebResult(name = "BookingRulesRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaBookingRules", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaBookingRules")
    @ResponseWrapper(localName = "VisaBookingRulesResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaBookingRulesResponse")
    public JPBookingRulesRS visaBookingRules(
        @WebParam(name = "VisaBookingRulesRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaBookingRulesRQ visaBookingRulesRQ);

}
