
package DAOs.JuniperAPIDAOs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaticDataTransactions", targetNamespace = "http://www.juniper.es/webservice/2007/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaticDataTransactions {


    /**
     * Generic Final Customer List
     * 
     * @param finalCustomerReadRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "FinalCustomerRead", action = "http://www.juniper.es/webservice/2007/FinalCustomerRead")
    @WebResult(name = "FinalCustomerReadRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "FinalCustomerRead", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FinalCustomerRead")
    @ResponseWrapper(localName = "FinalCustomerReadResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.FinalCustomerReadResponse")
    public JPStaticDataRS finalCustomerRead(
        @WebParam(name = "FinalCustomerReadRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPFinalCustomerRead finalCustomerReadRQ);

    /**
     * Generic Agency List
     * 
     * @param agencyReadRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "AgencyRead", action = "http://www.juniper.es/webservice/2007/AgencyRead")
    @WebResult(name = "AgencyReadRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "AgencyRead", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.AgencyRead")
    @ResponseWrapper(localName = "AgencyReadResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.AgencyReadResponse")
    public JPStaticDataRS agencyRead(
        @WebParam(name = "AgencyReadRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPAgencyRead agencyReadRQ);

    /**
     * Generic Supplier List
     * 
     * @param supplierListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "SupplierList", action = "http://www.juniper.es/webservice/2007/SupplierList")
    @WebResult(name = "SupplierListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "SupplierList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.SupplierList")
    @ResponseWrapper(localName = "SupplierListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.SupplierListResponse")
    public JPStaticDataRS supplierList(
        @WebParam(name = "SupplierListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPSupplierListRQ supplierListRQ);

    /**
     * Generic Data Catalogue Request
     * 
     * @param genericDataCatalogueRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "GenericDataCatalogue", action = "http://www.juniper.es/webservice/2007/GenericDataCatalogue")
    @WebResult(name = "GenericDataCatalogueRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "GenericDataCatalogue", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GenericDataCatalogue")
    @ResponseWrapper(localName = "GenericDataCatalogueResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GenericDataCatalogueResponse")
    public JPStaticDataRS genericDataCatalogue(
        @WebParam(name = "GenericDataCatalogueRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPGenericDataCatalogueRQ genericDataCatalogueRQ);

    /**
     * Generic Zone List
     * 
     * @param zoneListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "ZoneList", action = "http://www.juniper.es/webservice/2007/ZoneList")
    @WebResult(name = "ZoneListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ZoneList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ZoneList")
    @ResponseWrapper(localName = "ZoneListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ZoneListResponse")
    public JPStaticDataRS zoneList(
        @WebParam(name = "ZoneListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPZoneListRQ zoneListRQ);

    /**
     * Generic City List
     * 
     * @param cityListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "CityList", action = "http://www.juniper.es/webservice/2007/CityList")
    @WebResult(name = "CityListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CityList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CityList")
    @ResponseWrapper(localName = "CityListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CityListResponse")
    public JPStaticDataRS cityList(
        @WebParam(name = "CityListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCityListRQ cityListRQ);

    /**
     * Catalogue For Hotels
     * 
     * @param hotelCatalogueDataRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "HotelCatalogueData", action = "http://www.juniper.es/webservice/2007/HotelCatalogueData")
    @WebResult(name = "CatalogueDataRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelCatalogueData", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelCatalogueData")
    @ResponseWrapper(localName = "HotelCatalogueDataResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelCatalogueDataResponse")
    public JPStaticDataRS hotelCatalogueData(
        @WebParam(name = "HotelCatalogueDataRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelCatalogueDataRQ hotelCatalogueDataRQ);

    /**
     * List of Hotels
     * 
     * @param hotelListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "HotelList", action = "http://www.juniper.es/webservice/2007/HotelList")
    @WebResult(name = "HotelListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelList")
    @ResponseWrapper(localName = "HotelListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelListResponse")
    public JPStaticDataRS hotelList(
        @WebParam(name = "HotelListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelListRQ hotelListRQ);

    /**
     * Paged Portfolio of Hotels
     * 
     * @param hotelPortfolioRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "HotelPortfolio", action = "http://www.juniper.es/webservice/2007/HotelPortfolio")
    @WebResult(name = "HotelPortfolioRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelPortfolio", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelPortfolio")
    @ResponseWrapper(localName = "HotelPortfolioResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelPortfolioResponse")
    public JPStaticDataRS hotelPortfolio(
        @WebParam(name = "HotelPortfolioRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelPortfolioRQ hotelPortfolioRQ);

    /**
     * List of rooms
     * 
     * @param roomListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "RoomList", action = "http://www.juniper.es/webservice/2007/RoomList")
    @WebResult(name = "RoomListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RoomList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RoomList")
    @ResponseWrapper(localName = "RoomListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RoomListResponse")
    public JPStaticDataRS roomList(
        @WebParam(name = "RoomListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRoomListRQ roomListRQ);

    /**
     * List of itineraries.
     * 
     * @param cruiseItineraryRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "CruiseItinerary", action = "http://www.juniper.es/webservice/2007/CruiseItinerary")
    @WebResult(name = "CruiseItineraryRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseItinerary", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseItinerary")
    @ResponseWrapper(localName = "CruiseItineraryResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseItineraryResponse")
    public JPStaticDataRS cruiseItinerary(
        @WebParam(name = "CruiseItineraryRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseItineraryRQ cruiseItineraryRQ);

    /**
     * List of ships.
     * 
     * @param cruiseShipRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "CruiseShip", action = "http://www.juniper.es/webservice/2007/CruiseShip")
    @WebResult(name = "CruiseShipRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseShip", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseShip")
    @ResponseWrapper(localName = "CruiseShipResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseShipResponse")
    public JPStaticDataRS cruiseShip(
        @WebParam(name = "CruiseShipRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseShipRQ cruiseShipRQ);

    /**
     * List of Cruises Data.
     * 
     * @param cruiseDataRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "CruiseDataList", action = "http://www.juniper.es/webservice/2007/CruiseDataList")
    @WebResult(name = "CruiseDataRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "CruiseDataList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseDataList")
    @ResponseWrapper(localName = "CruiseDataListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.CruiseDataListResponse")
    public JPStaticDataRS cruiseDataList(
        @WebParam(name = "CruiseDataRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPCruiseDataRQ cruiseDataRQ);

    /**
     * List of Packages
     * 
     * @param packageListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "PackageList", action = "http://www.juniper.es/webservice/2007/PackageList")
    @WebResult(name = "PackageListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageList")
    @ResponseWrapper(localName = "PackageListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageListResponse")
    public JPStaticDataRS packageList(
        @WebParam(name = "PackageListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageListRQ packageListRQ);

    /**
     * Package calendar price
     * 
     * @param packageCalendarPriceRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "PackageCalendarPrice", action = "http://www.juniper.es/webservice/2007/PackageCalendarPrice")
    @WebResult(name = "PackageCalendarPriceRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageCalendarPrice", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageCalendarPrice")
    @ResponseWrapper(localName = "PackageCalendarPriceResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageCalendarPriceResponse")
    public JPStaticDataRS packageCalendarPrice(
        @WebParam(name = "PackageCalendarPriceRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageCalendarPriceRQ packageCalendarPriceRQ);

    /**
     * Various of Packages
     * 
     * @param packageSearcherRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "PackageSearcher", action = "http://www.juniper.es/webservice/2007/PackageSearcher")
    @WebResult(name = "PackageSearcherRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageSearcher", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageSearcher")
    @ResponseWrapper(localName = "PackageSearcherResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageSearcherResponse")
    public JPStaticDataRS packageSearcher(
        @WebParam(name = "PackageSearcherRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageSearcherRQ packageSearcherRQ);

    /**
     * List of rentacar locations
     * 
     * @param rentacarLocationListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "RentacarLocationList", action = "http://www.juniper.es/webservice/2007/RentacarLocationList")
    @WebResult(name = "RentacarLocationListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarLocationList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarLocationList")
    @ResponseWrapper(localName = "RentacarLocationListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarLocationListResponse")
    public JPStaticDataRS rentacarLocationList(
        @WebParam(name = "RentacarLocationListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarLocationListRQ rentacarLocationListRQ);

    /**
     * Catalogue For Services
     * 
     * @param serviceCatalogueDataRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "ServiceCatalogueData", action = "http://www.juniper.es/webservice/2007/ServiceCatalogueData")
    @WebResult(name = "CatalogueDataRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServiceCatalogueData", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceCatalogueData")
    @ResponseWrapper(localName = "ServiceCatalogueDataResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServiceCatalogueDataResponse")
    public JPStaticDataRS serviceCatalogueData(
        @WebParam(name = "ServiceCatalogueDataRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServiceCatalogueDataRQ serviceCatalogueDataRQ);

    /**
     * Paged Portfolio of Services
     * 
     * @param servicePortfolioRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "ServicePortfolio", action = "http://www.juniper.es/webservice/2007/ServicePortfolio")
    @WebResult(name = "ServicePortfolioRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "ServicePortfolio", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServicePortfolio")
    @ResponseWrapper(localName = "ServicePortfolioResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.ServicePortfolioResponse")
    public JPStaticDataRS servicePortfolio(
        @WebParam(name = "ServicePortfolioRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPServicePortfolioRQ servicePortfolioRQ);

    /**
     * Paged Portfolio of Transfers
     * 
     * @param transferPortfolioRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "TransferPortfolio", action = "http://www.juniper.es/webservice/2007/TransferPortfolio")
    @WebResult(name = "TransferPortfolioRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferPortfolio", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferPortfolio")
    @ResponseWrapper(localName = "TransferPortfolioResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferPortfolioResponse")
    public JPStaticDataRS transferPortfolio(
        @WebParam(name = "TransferPortfolioRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferPortfolioRQ transferPortfolioRQ);

    /**
     * Paged Portfolio of Visas
     * 
     * @param visaPortfolioRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "VisaPortfolio", action = "http://www.juniper.es/webservice/2007/VisaPortfolio")
    @WebResult(name = "VisaPortfolioRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaPortfolio", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaPortfolio")
    @ResponseWrapper(localName = "VisaPortfolioResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaPortfolioResponse")
    public JPStaticDataRS visaPortfolio(
        @WebParam(name = "VisaPortfolioRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaPortfolioRQ visaPortfolioRQ);

    /**
     * Catalogue For Transfers
     * 
     * @param transferCatalogueDataRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "TransferCatalogueData", action = "http://www.juniper.es/webservice/2007/TransferCatalogueData")
    @WebResult(name = "CatalogueDataRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "TransferCatalogueData", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferCatalogueData")
    @ResponseWrapper(localName = "TransferCatalogueDataResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.TransferCatalogueDataResponse")
    public JPStaticDataRS transferCatalogueData(
        @WebParam(name = "TransferCatalogueDataRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPTransferCatalogueDataRQ transferCatalogueDataRQ);

    /**
     * Catalogue For Visas
     * 
     * @param visaCatalogueDataRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "VisaCatalogueData", action = "http://www.juniper.es/webservice/2007/VisaCatalogueData")
    @WebResult(name = "CatalogueDataRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "VisaCatalogueData", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaCatalogueData")
    @ResponseWrapper(localName = "VisaCatalogueDataResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.VisaCatalogueDataResponse")
    public JPStaticDataRS visaCatalogueData(
        @WebParam(name = "VisaCatalogueDataRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPVisaCatalogueDataRQ visaCatalogueDataRQ);

    /**
     * Meeting Point List
     * 
     * @param meetingPointListRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "MeetingPointList", action = "http://www.juniper.es/webservice/2007/MeetingPointList")
    @WebResult(name = "MeetingPointListRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "MeetingPointList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.MeetingPointList")
    @ResponseWrapper(localName = "MeetingPointListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.MeetingPointListResponse")
    public JPStaticDataRS meetingPointList(
        @WebParam(name = "MeetingPointListRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPMeetingPointListRQ meetingPointListRQ);

    /**
     * Performs a request to read the search zones list.
     * 
     * @param zoneInfoRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "GetZoneInfoList", action = "http://www.juniper.es/webservice/2007/GetZoneInfoList")
    @WebResult(name = "ZoneInfoRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "GetZoneInfoList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GetZoneInfoList")
    @ResponseWrapper(localName = "GetZoneInfoListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GetZoneInfoListResponse")
    public JPStaticDataRS getZoneInfoList(
        @WebParam(name = "ZoneInfoRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPZoneInfoRQ zoneInfoRQ);

    /**
     * Performs a request to read the user permissions.
     * 
     * @param userPermissionsRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPStaticDataRS
     */
    @WebMethod(operationName = "GetPermissionList", action = "http://www.juniper.es/webservice/2007/GetPermissionList")
    @WebResult(name = "UserPermissionsRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "GetPermissionList", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GetPermissionList")
    @ResponseWrapper(localName = "GetPermissionListResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.GetPermissionListResponse")
    public JPStaticDataRS getPermissionList(
        @WebParam(name = "UserPermissionsRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPUserPermissionsRQ userPermissionsRQ);

    /**
     * Content Of Hotels
     * 
     * @param hotelContentRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPContentRS
     */
    @WebMethod(operationName = "HotelContent", action = "http://www.juniper.es/webservice/2007/HotelContent")
    @WebResult(name = "ContentRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "HotelContent", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelContent")
    @ResponseWrapper(localName = "HotelContentResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.HotelContentResponse")
    public JPContentRS hotelContent(
        @WebParam(name = "HotelContentRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPHotelContentRQ hotelContentRQ);

    /**
     * Content Of Packages
     * 
     * @param packageContentRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPContentRS
     */
    @WebMethod(operationName = "PackageContent", action = "http://www.juniper.es/webservice/2007/PackageContent")
    @WebResult(name = "ContentRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "PackageContent", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageContent")
    @ResponseWrapper(localName = "PackageContentResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.PackageContentResponse")
    public JPContentRS packageContent(
        @WebParam(name = "PackageContentRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPPackageContentRQ packageContentRQ);

    /**
     * Content Of Rentacar Locations
     * 
     * @param rentacarLocationContentRQ
     * @return
     *     returns DAOs.JuniperAPIDAOs.JPContentRS
     */
    @WebMethod(operationName = "RentacarLocationContent", action = "http://www.juniper.es/webservice/2007/RentacarLocationContent")
    @WebResult(name = "ContentRS", targetNamespace = "http://www.juniper.es/webservice/2007/")
    @RequestWrapper(localName = "RentacarLocationContent", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarLocationContent")
    @ResponseWrapper(localName = "RentacarLocationContentResponse", targetNamespace = "http://www.juniper.es/webservice/2007/", className = "DAOs.JuniperAPIDAOs.RentacarLocationContentResponse")
    public JPContentRS rentacarLocationContent(
        @WebParam(name = "RentacarLocationContentRQ", targetNamespace = "http://www.juniper.es/webservice/2007/")
        JPRentacarLocationContentRQ rentacarLocationContentRQ);

}
