
package DAOs.SunHotelsAPIDAOs;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NonStaticXMLAPISoap", targetNamespace = "http://xml.sunhotels.net/15/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NonStaticXMLAPISoap {


    /**
     * 
     * @param childrenGuest7LastName
     * @param yourRef
     * @param rooms
     * @param adultGuest1LastName
     * @param adultGuest3FirstName
     * @param adultGuest6FirstName
     * @param mealId
     * @param adultGuest3LastName
     * @param childrenGuest9LastName
     * @param language
     * @param childrenGuest7FirstName
     * @param childrenGuest5LastName
     * @param creditCardType
     * @param infant
     * @param roomId
     * @param password
     * @param checkOutDate
     * @param children
     * @param childrenGuest3LastName
     * @param customerEmail
     * @param childrenGuest1LastName
     * @param adultGuest9LastName
     * @param preBookCode
     * @param adultGuest7LastName
     * @param adultGuest4FirstName
     * @param childrenGuest9FirstName
     * @param b2C
     * @param creditCardNumber
     * @param childrenGuest4FirstName
     * @param adultGuest9FirstName
     * @param adultGuest5LastName
     * @param childrenGuestAge4
     * @param childrenGuestAge5
     * @param childrenGuestAge2
     * @param childrenGuestAge3
     * @param childrenGuest8LastName
     * @param childrenGuestAge1
     * @param childrenGuest6LastName
     * @param creditCardExpMonth
     * @param adults
     * @param commissionAmountInHotelCurrency
     * @param creditCardExpYear
     * @param checkInDate
     * @param childrenGuest4LastName
     * @param customerCountry
     * @param adultGuest2LastName
     * @param invoiceRef
     * @param adultGuest5FirstName
     * @param childrenGuest2LastName
     * @param childrenGuest3FirstName
     * @param adultGuest8FirstName
     * @param paymentMethodId
     * @param currency
     * @param childrenGuest5FirstName
     * @param adultGuest2FirstName
     * @param childrenGuestAge8
     * @param childrenGuest8FirstName
     * @param childrenGuestAge9
     * @param email
     * @param childrenGuestAge6
     * @param childrenGuestAge7
     * @param specialrequest
     * @param creditCardHolder
     * @param adultGuest7FirstName
     * @param childrenGuest2FirstName
     * @param userName
     * @param adultGuest8LastName
     * @param childrenGuest6FirstName
     * @param adultGuest4LastName
     * @param adultGuest6LastName
     * @param creditCardCVV2
     * @param adultGuest1FirstName
     * @param childrenGuest1FirstName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.BookResult
     */
    @WebMethod(operationName = "BookV2", action = "http://xml.sunhotels.net/15/BookV2")
    @WebResult(name = "bookResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "BookV2", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.BookV2")
    @ResponseWrapper(localName = "BookV2Response", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.BookV2Response")
    public BookResult bookV2(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "currency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currency,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "email", targetNamespace = "http://xml.sunhotels.net/15/")
                    String email,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "roomId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int roomId,
            @WebParam(name = "rooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int rooms,
            @WebParam(name = "adults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int adults,
            @WebParam(name = "children", targetNamespace = "http://xml.sunhotels.net/15/")
                    int children,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "yourRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String yourRef,
            @WebParam(name = "specialrequest", targetNamespace = "http://xml.sunhotels.net/15/")
                    String specialrequest,
            @WebParam(name = "mealId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int mealId,
            @WebParam(name = "adultGuest1FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest1FirstName,
            @WebParam(name = "adultGuest1LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest1LastName,
            @WebParam(name = "adultGuest2FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest2FirstName,
            @WebParam(name = "adultGuest2LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest2LastName,
            @WebParam(name = "adultGuest3FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest3FirstName,
            @WebParam(name = "adultGuest3LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest3LastName,
            @WebParam(name = "adultGuest4FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest4FirstName,
            @WebParam(name = "adultGuest4LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest4LastName,
            @WebParam(name = "adultGuest5FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest5FirstName,
            @WebParam(name = "adultGuest5LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest5LastName,
            @WebParam(name = "adultGuest6FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest6FirstName,
            @WebParam(name = "adultGuest6LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest6LastName,
            @WebParam(name = "adultGuest7FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest7FirstName,
            @WebParam(name = "adultGuest7LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest7LastName,
            @WebParam(name = "adultGuest8FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest8FirstName,
            @WebParam(name = "adultGuest8LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest8LastName,
            @WebParam(name = "adultGuest9FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest9FirstName,
            @WebParam(name = "adultGuest9LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest9LastName,
            @WebParam(name = "childrenGuest1FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest1FirstName,
            @WebParam(name = "childrenGuest1LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest1LastName,
            @WebParam(name = "childrenGuestAge1", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge1,
            @WebParam(name = "childrenGuest2FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest2FirstName,
            @WebParam(name = "childrenGuest2LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest2LastName,
            @WebParam(name = "childrenGuestAge2", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge2,
            @WebParam(name = "childrenGuest3FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest3FirstName,
            @WebParam(name = "childrenGuest3LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest3LastName,
            @WebParam(name = "childrenGuestAge3", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge3,
            @WebParam(name = "childrenGuest4FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest4FirstName,
            @WebParam(name = "childrenGuest4LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest4LastName,
            @WebParam(name = "childrenGuestAge4", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge4,
            @WebParam(name = "childrenGuest5FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest5FirstName,
            @WebParam(name = "childrenGuest5LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest5LastName,
            @WebParam(name = "childrenGuestAge5", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge5,
            @WebParam(name = "childrenGuest6FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest6FirstName,
            @WebParam(name = "childrenGuest6LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest6LastName,
            @WebParam(name = "childrenGuestAge6", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge6,
            @WebParam(name = "childrenGuest7FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest7FirstName,
            @WebParam(name = "childrenGuest7LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest7LastName,
            @WebParam(name = "childrenGuestAge7", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge7,
            @WebParam(name = "childrenGuest8FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest8FirstName,
            @WebParam(name = "childrenGuest8LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest8LastName,
            @WebParam(name = "childrenGuestAge8", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge8,
            @WebParam(name = "childrenGuest9FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest9FirstName,
            @WebParam(name = "childrenGuest9LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest9LastName,
            @WebParam(name = "childrenGuestAge9", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge9,
            @WebParam(name = "paymentMethodId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int paymentMethodId,
            @WebParam(name = "creditCardType", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardType,
            @WebParam(name = "creditCardNumber", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardNumber,
            @WebParam(name = "creditCardHolder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardHolder,
            @WebParam(name = "creditCardCVV2", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardCVV2,
            @WebParam(name = "creditCardExpYear", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardExpYear,
            @WebParam(name = "creditCardExpMonth", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardExpMonth,
            @WebParam(name = "customerEmail", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerEmail,
            @WebParam(name = "invoiceRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String invoiceRef,
            @WebParam(name = "customerCountry", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerCountry,
            @WebParam(name = "b2c", targetNamespace = "http://xml.sunhotels.net/15/")
                    String b2C,
            @WebParam(name = "commissionAmountInHotelCurrency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String commissionAmountInHotelCurrency,
            @WebParam(name = "preBookCode", targetNamespace = "http://xml.sunhotels.net/15/")
                    String preBookCode);

    /**
     * 
     * @param rooms
     * @param mealId
     * @param searchPrice
     * @param adults
     * @param language
     * @param userName
     * @param infant
     * @param checkInDate
     * @param roomId
     * @param customerCountry
     * @param childrenAges
     * @param password
     * @param b2C
     * @param checkOutDate
     * @param children
     * @param currency
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.PreBookResult
     */
    @WebMethod(operationName = "PreBook", action = "http://xml.sunhotels.net/15/PreBook")
    @WebResult(name = "preBookResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "PreBook", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.PreBook")
    @ResponseWrapper(localName = "PreBookResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.PreBookResponse")
    public PreBookResult preBook(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "currency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currency,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "rooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int rooms,
            @WebParam(name = "adults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int adults,
            @WebParam(name = "children", targetNamespace = "http://xml.sunhotels.net/15/")
                    int children,
            @WebParam(name = "childrenAges", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenAges,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "mealId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int mealId,
            @WebParam(name = "searchPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String searchPrice,
            @WebParam(name = "roomId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String roomId,
            @WebParam(name = "customerCountry", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerCountry,
            @WebParam(name = "b2c", targetNamespace = "http://xml.sunhotels.net/15/")
                    String b2C);

    /**
     * 
     * @param rooms
     * @param mealId
     * @param showPriceBreakdown
     * @param searchPrice
     * @param adults
     * @param roomtypeId
     * @param language
     * @param hotelId
     * @param userName
     * @param infant
     * @param checkInDate
     * @param customerCountry
     * @param roomId
     * @param childrenAges
     * @param blockSuperDeal
     * @param password
     * @param b2C
     * @param checkOutDate
     * @param children
     * @param currency
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.PreBookResult
     */
    @WebMethod(operationName = "PreBookV2", action = "http://xml.sunhotels.net/15/PreBookV2")
    @WebResult(name = "preBookResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "PreBookV2", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.PreBookV2")
    @ResponseWrapper(localName = "PreBookV2Response", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.PreBookV2Response")
    public PreBookResult preBookV2(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "currency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currency,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "rooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int rooms,
            @WebParam(name = "adults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int adults,
            @WebParam(name = "children", targetNamespace = "http://xml.sunhotels.net/15/")
                    int children,
            @WebParam(name = "childrenAges", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenAges,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "mealId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int mealId,
            @WebParam(name = "customerCountry", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerCountry,
            @WebParam(name = "b2c", targetNamespace = "http://xml.sunhotels.net/15/")
                    String b2C,
            @WebParam(name = "searchPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String searchPrice,
            @WebParam(name = "roomId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String roomId,
            @WebParam(name = "hotelId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelId,
            @WebParam(name = "roomtypeId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String roomtypeId,
            @WebParam(name = "blockSuperDeal", targetNamespace = "http://xml.sunhotels.net/15/")
                    String blockSuperDeal,
            @WebParam(name = "showPriceBreakdown", targetNamespace = "http://xml.sunhotels.net/15/")
                    String showPriceBreakdown);

    /**
     * 
     * @param returnDepartureTime
     * @param resortID
     * @param language
     * @param hotelID
     * @param userName
     * @param transferID
     * @param roomID
     * @param bookingID
     * @param arrivalDate
     * @param password
     * @param arrivalTime
     * @param returnDepartureDate
     * @param currencies
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.SearchTransfersResult
     */
    @WebMethod(operationName = "SearchTransfers", action = "http://xml.sunhotels.net/15/SearchTransfers")
    @WebResult(name = "searchTransfersResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "SearchTransfers", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.SearchTransfers")
    @ResponseWrapper(localName = "SearchTransfersResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.SearchTransfersResponse")
    public SearchTransfersResult searchTransfers(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "currencies", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currencies,
            @WebParam(name = "hotelID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelID,
            @WebParam(name = "roomID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String roomID,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "resortID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String resortID,
            @WebParam(name = "transferID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String transferID,
            @WebParam(name = "arrivalDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDate,
            @WebParam(name = "arrivalTime", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalTime,
            @WebParam(name = "returnDepartureDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnDepartureDate,
            @WebParam(name = "returnDepartureTime", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnDepartureTime);

    /**
     * 
     * @param departureTime
     * @param yourRef
     * @param passengers
     * @param returnDepartureTime
     * @param departureAirport
     * @param returnFlightNumber
     * @param contactPerson
     * @param language
     * @param contactCellphone
     * @param userName
     * @param transferID
     * @param hotelName
     * @param bookingID
     * @param flightNumber
     * @param arrivalDate
     * @param password
     * @param returnTransfer
     * @param invoiceRef
     * @param arrivalTime
     * @param returnAirline
     * @param returnDepartureDate
     * @param currency
     * @param airline
     * @param email
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.AddTransferResult
     */
    @WebMethod(operationName = "AddTransfer", action = "http://xml.sunhotels.net/15/AddTransfer")
    @WebResult(name = "addTransferResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "AddTransfer", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AddTransfer")
    @ResponseWrapper(localName = "AddTransferResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AddTransferResponse")
    public AddTransferResult addTransfer(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "currency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currency,
            @WebParam(name = "email", targetNamespace = "http://xml.sunhotels.net/15/")
                    String email,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "hotelName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelName,
            @WebParam(name = "contactPerson", targetNamespace = "http://xml.sunhotels.net/15/")
                    String contactPerson,
            @WebParam(name = "contactCellphone", targetNamespace = "http://xml.sunhotels.net/15/")
                    String contactCellphone,
            @WebParam(name = "airline", targetNamespace = "http://xml.sunhotels.net/15/")
                    String airline,
            @WebParam(name = "flightNumber", targetNamespace = "http://xml.sunhotels.net/15/")
                    String flightNumber,
            @WebParam(name = "departureAirport", targetNamespace = "http://xml.sunhotels.net/15/")
                    String departureAirport,
            @WebParam(name = "departureTime", targetNamespace = "http://xml.sunhotels.net/15/")
                    String departureTime,
            @WebParam(name = "arrivalTime", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalTime,
            @WebParam(name = "arrivalDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDate,
            @WebParam(name = "passengers", targetNamespace = "http://xml.sunhotels.net/15/")
                    int passengers,
            @WebParam(name = "transferID", targetNamespace = "http://xml.sunhotels.net/15/")
                    int transferID,
            @WebParam(name = "returnTransfer", targetNamespace = "http://xml.sunhotels.net/15/")
                    int returnTransfer,
            @WebParam(name = "returnAirline", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnAirline,
            @WebParam(name = "returnFlightNumber", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnFlightNumber,
            @WebParam(name = "returnDepartureDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnDepartureDate,
            @WebParam(name = "returnDepartureTime", targetNamespace = "http://xml.sunhotels.net/15/")
                    String returnDepartureTime,
            @WebParam(name = "invoiceRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String invoiceRef,
            @WebParam(name = "yourRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String yourRef);

    /**
     * 
     * @param childrenGuest7LastName
     * @param yourRef
     * @param rooms
     * @param adultGuest1LastName
     * @param adultGuest3FirstName
     * @param adultGuest6FirstName
     * @param mealId
     * @param adultGuest3LastName
     * @param childrenGuest9LastName
     * @param language
     * @param childrenGuest7FirstName
     * @param childrenGuest5LastName
     * @param creditCardType
     * @param infant
     * @param roomId
     * @param password
     * @param checkOutDate
     * @param children
     * @param childrenGuest3LastName
     * @param customerEmail
     * @param childrenGuest1LastName
     * @param adultGuest9LastName
     * @param adultGuest7LastName
     * @param adultGuest4FirstName
     * @param childrenGuest9FirstName
     * @param creditCardNumber
     * @param childrenGuest4FirstName
     * @param adultGuest9FirstName
     * @param adultGuest5LastName
     * @param childrenGuestAge4
     * @param childrenGuestAge5
     * @param childrenGuestAge2
     * @param childrenGuestAge3
     * @param childrenGuest8LastName
     * @param childrenGuestAge1
     * @param childrenGuest6LastName
     * @param creditCardExpMonth
     * @param adults
     * @param creditCardExpYear
     * @param checkInDate
     * @param childrenGuest4LastName
     * @param adultGuest2LastName
     * @param invoiceRef
     * @param adultGuest5FirstName
     * @param childrenGuest2LastName
     * @param childrenGuest3FirstName
     * @param adultGuest8FirstName
     * @param paymentMethodId
     * @param currency
     * @param childrenGuest5FirstName
     * @param adultGuest2FirstName
     * @param childrenGuestAge8
     * @param childrenGuest8FirstName
     * @param childrenGuestAge9
     * @param email
     * @param childrenGuestAge6
     * @param childrenGuestAge7
     * @param specialrequest
     * @param creditCardHolder
     * @param adultGuest7FirstName
     * @param childrenGuest2FirstName
     * @param userName
     * @param adultGuest8LastName
     * @param childrenGuest6FirstName
     * @param adultGuest4LastName
     * @param adultGuest6LastName
     * @param creditCardCVV2
     * @param adultGuest1FirstName
     * @param childrenGuest1FirstName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.BookResult
     */
    @WebMethod(operationName = "Book", action = "http://xml.sunhotels.net/15/Book")
    @WebResult(name = "bookResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "Book", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.Book")
    @ResponseWrapper(localName = "BookResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.BookResponse")
    public BookResult book(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "currency", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currency,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "email", targetNamespace = "http://xml.sunhotels.net/15/")
                    String email,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "roomId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int roomId,
            @WebParam(name = "rooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int rooms,
            @WebParam(name = "adults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int adults,
            @WebParam(name = "children", targetNamespace = "http://xml.sunhotels.net/15/")
                    int children,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "yourRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String yourRef,
            @WebParam(name = "specialrequest", targetNamespace = "http://xml.sunhotels.net/15/")
                    String specialrequest,
            @WebParam(name = "mealId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int mealId,
            @WebParam(name = "adultGuest1FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest1FirstName,
            @WebParam(name = "adultGuest1LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest1LastName,
            @WebParam(name = "adultGuest2FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest2FirstName,
            @WebParam(name = "adultGuest2LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest2LastName,
            @WebParam(name = "adultGuest3FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest3FirstName,
            @WebParam(name = "adultGuest3LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest3LastName,
            @WebParam(name = "adultGuest4FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest4FirstName,
            @WebParam(name = "adultGuest4LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest4LastName,
            @WebParam(name = "adultGuest5FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest5FirstName,
            @WebParam(name = "adultGuest5LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest5LastName,
            @WebParam(name = "adultGuest6FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest6FirstName,
            @WebParam(name = "adultGuest6LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest6LastName,
            @WebParam(name = "adultGuest7FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest7FirstName,
            @WebParam(name = "adultGuest7LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest7LastName,
            @WebParam(name = "adultGuest8FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest8FirstName,
            @WebParam(name = "adultGuest8LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest8LastName,
            @WebParam(name = "adultGuest9FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest9FirstName,
            @WebParam(name = "adultGuest9LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String adultGuest9LastName,
            @WebParam(name = "childrenGuest1FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest1FirstName,
            @WebParam(name = "childrenGuest1LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest1LastName,
            @WebParam(name = "childrenGuestAge1", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge1,
            @WebParam(name = "childrenGuest2FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest2FirstName,
            @WebParam(name = "childrenGuest2LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest2LastName,
            @WebParam(name = "childrenGuestAge2", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge2,
            @WebParam(name = "childrenGuest3FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest3FirstName,
            @WebParam(name = "childrenGuest3LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest3LastName,
            @WebParam(name = "childrenGuestAge3", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge3,
            @WebParam(name = "childrenGuest4FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest4FirstName,
            @WebParam(name = "childrenGuest4LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest4LastName,
            @WebParam(name = "childrenGuestAge4", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge4,
            @WebParam(name = "childrenGuest5FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest5FirstName,
            @WebParam(name = "childrenGuest5LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest5LastName,
            @WebParam(name = "childrenGuestAge5", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge5,
            @WebParam(name = "childrenGuest6FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest6FirstName,
            @WebParam(name = "childrenGuest6LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest6LastName,
            @WebParam(name = "childrenGuestAge6", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge6,
            @WebParam(name = "childrenGuest7FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest7FirstName,
            @WebParam(name = "childrenGuest7LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest7LastName,
            @WebParam(name = "childrenGuestAge7", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge7,
            @WebParam(name = "childrenGuest8FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest8FirstName,
            @WebParam(name = "childrenGuest8LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest8LastName,
            @WebParam(name = "childrenGuestAge8", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge8,
            @WebParam(name = "childrenGuest9FirstName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest9FirstName,
            @WebParam(name = "childrenGuest9LastName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuest9LastName,
            @WebParam(name = "childrenGuestAge9", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenGuestAge9,
            @WebParam(name = "paymentMethodId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int paymentMethodId,
            @WebParam(name = "creditCardType", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardType,
            @WebParam(name = "creditCardNumber", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardNumber,
            @WebParam(name = "creditCardHolder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardHolder,
            @WebParam(name = "creditCardCVV2", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardCVV2,
            @WebParam(name = "creditCardExpYear", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardExpYear,
            @WebParam(name = "creditCardExpMonth", targetNamespace = "http://xml.sunhotels.net/15/")
                    String creditCardExpMonth,
            @WebParam(name = "customerEmail", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerEmail,
            @WebParam(name = "invoiceRef", targetNamespace = "http://xml.sunhotels.net/15/")
                    String invoiceRef);

    /**
     * 
     * @param password
     * @param hotelIDs
     * @param resortIDs
     * @param sortOrder
     * @param destination
     * @param exactDestinationMatch
     * @param language
     * @param sortBy
     * @param userName
     * @param accommodationTypes
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetStaticHotelsAndRoomsResult
     */
    @WebMethod(operationName = "GetStaticHotelsAndRooms", action = "http://xml.sunhotels.net/15/GetStaticHotelsAndRooms")
    @WebResult(name = "getStaticHotelsAndRoomsResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetStaticHotelsAndRooms", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetStaticHotelsAndRooms")
    @ResponseWrapper(localName = "GetStaticHotelsAndRoomsResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetStaticHotelsAndRoomsResponse")
    public GetStaticHotelsAndRoomsResult getStaticHotelsAndRooms(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "destination", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destination,
            @WebParam(name = "hotelIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelIDs,
            @WebParam(name = "resortIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String resortIDs,
            @WebParam(name = "accommodationTypes", targetNamespace = "http://xml.sunhotels.net/15/")
                    String accommodationTypes,
            @WebParam(name = "sortBy", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortBy,
            @WebParam(name = "sortOrder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortOrder,
            @WebParam(name = "exactDestinationMatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String exactDestinationMatch);

    /**
     * 
     * @param password
     * @param destinationCode
     * @param sortOrder
     * @param exactDestinationMatch
     * @param language
     * @param sortBy
     * @param userName
     * @param destinationID
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.ResortList
     */
    @WebMethod(operationName = "GetResorts", action = "http://xml.sunhotels.net/15/GetResorts")
    @WebResult(name = "GetResortsResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetResorts", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetResorts")
    @ResponseWrapper(localName = "GetResortsResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetResortsResponse")
    public ResortList getResorts(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "destinationCode", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destinationCode,
            @WebParam(name = "destinationID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destinationID,
            @WebParam(name = "sortBy", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortBy,
            @WebParam(name = "sortOrder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortOrder,
            @WebParam(name = "exactDestinationMatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String exactDestinationMatch);

    /**
     * 
     * @param reference
     * @param password
     * @param createdDateFrom
     * @param createdDateTo
     * @param arrivalDateFrom
     * @param language
     * @param userName
     * @param bookingID
     * @param arrivalDateTo
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetBookingInformationResult
     */
    @WebMethod(operationName = "GetBookingInformation", action = "http://xml.sunhotels.net/15/GetBookingInformation")
    @WebResult(name = "getBookingInformationResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetBookingInformation", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetBookingInformation")
    @ResponseWrapper(localName = "GetBookingInformationResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetBookingInformationResponse")
    public GetBookingInformationResult getBookingInformation(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "reference", targetNamespace = "http://xml.sunhotels.net/15/")
                    String reference,
            @WebParam(name = "createdDateFrom", targetNamespace = "http://xml.sunhotels.net/15/")
                    String createdDateFrom,
            @WebParam(name = "createdDateTo", targetNamespace = "http://xml.sunhotels.net/15/")
                    String createdDateTo,
            @WebParam(name = "arrivalDateFrom", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDateFrom,
            @WebParam(name = "arrivalDateTo", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDateTo);

    /**
     * 
     * @param password
     * @param destinationCode
     * @param sortOrder
     * @param exactDestinationMatch
     * @param language
     * @param sortBy
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.DestinationList
     */
    @WebMethod(operationName = "GetDestinations", action = "http://xml.sunhotels.net/15/GetDestinations")
    @WebResult(name = "GetDestinationsResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetDestinations", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetDestinations")
    @ResponseWrapper(localName = "GetDestinationsResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetDestinationsResponse")
    public DestinationList getDestinations(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "destinationCode", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destinationCode,
            @WebParam(name = "sortBy", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortBy,
            @WebParam(name = "sortOrder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortOrder,
            @WebParam(name = "exactDestinationMatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String exactDestinationMatch);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetThemesResult
     */
    @WebMethod(operationName = "GetThemes", action = "http://xml.sunhotels.net/15/GetThemes")
    @WebResult(name = "getThemesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetThemes", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetThemes")
    @ResponseWrapper(localName = "GetThemesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetThemesResponse")
    public GetThemesResult getThemes(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password);

    /**
     * 
     * @param password
     * @param transferTypeCode
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetTransferTypesResult
     */
    @WebMethod(operationName = "GetTransferTypes", action = "http://xml.sunhotels.net/15/GetTransferTypes")
    @WebResult(name = "getTransferTypesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetTransferTypes", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetTransferTypes")
    @ResponseWrapper(localName = "GetTransferTypesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetTransferTypesResponse")
    public GetTransferTypesResult getTransferTypes(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "transferTypeCode", targetNamespace = "http://xml.sunhotels.net/15/")
                    String transferTypeCode);

    /**
     * 
     * @param password
     * @param createdDateFrom
     * @param createdDateTo
     * @param arrivalDateFrom
     * @param language
     * @param userName
     * @param bookingID
     * @param arrivalDateTo
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetTransferBookingInformationResult
     */
    @WebMethod(operationName = "GetTransferBookingInformation", action = "http://xml.sunhotels.net/15/GetTransferBookingInformation")
    @WebResult(name = "getTransferBookingInformationResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetTransferBookingInformation", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetTransferBookingInformation")
    @ResponseWrapper(localName = "GetTransferBookingInformationResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetTransferBookingInformationResponse")
    public GetTransferBookingInformationResult getTransferBookingInformation(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    int bookingID,
            @WebParam(name = "createdDateFrom", targetNamespace = "http://xml.sunhotels.net/15/")
                    String createdDateFrom,
            @WebParam(name = "createdDateTo", targetNamespace = "http://xml.sunhotels.net/15/")
                    String createdDateTo,
            @WebParam(name = "arrivalDateFrom", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDateFrom,
            @WebParam(name = "arrivalDateTo", targetNamespace = "http://xml.sunhotels.net/15/")
                    String arrivalDateTo);

    /**
     * 
     * @param password
     * @param text
     * @param userName
     * @param bookingId
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.UpdateSpecialRequestResult
     */
    @WebMethod(operationName = "UpdateSpecialRequest", action = "http://xml.sunhotels.net/15/UpdateSpecialRequest")
    @WebResult(name = "updateSpecialRequestResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "UpdateSpecialRequest", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.UpdateSpecialRequest")
    @ResponseWrapper(localName = "UpdateSpecialRequestResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.UpdateSpecialRequestResponse")
    public UpdateSpecialRequestResult updateSpecialRequest(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "bookingId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int bookingId,
            @WebParam(name = "text", targetNamespace = "http://xml.sunhotels.net/15/")
                    String text);

    /**
     * 
     * @param password
     * @param userName
     * @param bookingId
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetSpecialRequestResult
     */
    @WebMethod(operationName = "GetSpecialRequest", action = "http://xml.sunhotels.net/15/GetSpecialRequest")
    @WebResult(name = "getSpecialRequestResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetSpecialRequest", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetSpecialRequest")
    @ResponseWrapper(localName = "GetSpecialRequestResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetSpecialRequestResponse")
    public GetSpecialRequestResult getSpecialRequest(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "bookingId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int bookingId);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetHotelNoteTypesResult
     */
    @WebMethod(operationName = "GetHotelNoteTypes", action = "http://xml.sunhotels.net/15/GetHotelNoteTypes")
    @WebResult(name = "getHotelNoteTypesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetHotelNoteTypes", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetHotelNoteTypes")
    @ResponseWrapper(localName = "GetHotelNoteTypesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetHotelNoteTypesResponse")
    public GetHotelNoteTypesResult getHotelNoteTypes(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetRoomNoteTypesResult
     */
    @WebMethod(operationName = "GetRoomNoteTypes", action = "http://xml.sunhotels.net/15/GetRoomNoteTypes")
    @WebResult(name = "getRoomNoteTypesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetRoomNoteTypes", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetRoomNoteTypes")
    @ResponseWrapper(localName = "GetRoomNoteTypesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetRoomNoteTypesResponse")
    public GetRoomNoteTypesResult getRoomNoteTypes(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param checkOutDate
     * @param language
     * @param userName
     * @param checkInDate
     * @param bookingID
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.AmendmentPriceRequestResult
     */
    @WebMethod(operationName = "AmendmentPriceRequest", action = "http://xml.sunhotels.net/15/AmendmentPriceRequest")
    @WebResult(name = "amendmentPriceRequestResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "AmendmentPriceRequest", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AmendmentPriceRequest")
    @ResponseWrapper(localName = "AmendmentPriceRequestResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AmendmentPriceRequestResponse")
    public AmendmentPriceRequestResult amendmentPriceRequest(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param checkOutDate
     * @param bookingType
     * @param language
     * @param maxPrice
     * @param userName
     * @param checkInDate
     * @param bookingID
     * @param roomId
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.AmendmentRequestResult
     */
    @WebMethod(operationName = "AmendmentRequest", action = "http://xml.sunhotels.net/15/AmendmentRequest")
    @WebResult(name = "amendmentRequestResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "AmendmentRequest", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AmendmentRequest")
    @ResponseWrapper(localName = "AmendmentRequestResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.AmendmentRequestResponse")
    public AmendmentRequestResult amendmentRequest(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "roomId", targetNamespace = "http://xml.sunhotels.net/15/")
                    int roomId,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "maxPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    BigDecimal maxPrice,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "bookingType", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingType);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetRoomTypesResult
     */
    @WebMethod(operationName = "GetRoomTypes", action = "http://xml.sunhotels.net/15/GetRoomTypes")
    @WebResult(name = "getRoomTypesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetRoomTypes", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetRoomTypes")
    @ResponseWrapper(localName = "GetRoomTypesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetRoomTypesResponse")
    public GetRoomTypesResult getRoomTypes(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @param bookingID
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.CancellationResult
     */
    @WebMethod(operationName = "CancelBooking", action = "http://xml.sunhotels.net/15/CancelBooking")
    @WebResult(name = "result", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.CancelBookingResponse")
    public CancellationResult cancelBooking(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "bookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String bookingID,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param transferBookingID
     * @param language
     * @param userName
     * @param email
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.CancelTransferBookingResult
     */
    @WebMethod(operationName = "CancelTransferBooking", action = "http://xml.sunhotels.net/15/CancelTransferBooking")
    @WebResult(name = "cancelTransferBookingResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "CancelTransferBooking", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.CancelTransferBooking")
    @ResponseWrapper(localName = "CancelTransferBookingResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.CancelTransferBookingResponse")
    public CancelTransferBookingResult cancelTransferBooking(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "email", targetNamespace = "http://xml.sunhotels.net/15/")
                    String email,
            @WebParam(name = "transferBookingID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String transferBookingID);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetMealsResult
     */
    @WebMethod(operationName = "GetMeals", action = "http://xml.sunhotels.net/15/GetMeals")
    @WebResult(name = "getMealsResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetMeals", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetMeals")
    @ResponseWrapper(localName = "GetMealsResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetMealsResponse")
    public GetMealsResult getMeals(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetLanguagesResult
     */
    @WebMethod(operationName = "GetLanguages", action = "http://xml.sunhotels.net/15/GetLanguages")
    @WebResult(name = "getLanguagesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetLanguagesResponse")
    public GetLanguagesResult getLanguages(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password);

    /**
     * 
     * @param password
     * @param language
     * @param userName
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.GetFeaturesResult
     */
    @WebMethod(operationName = "GetFeatures", action = "http://xml.sunhotels.net/15/GetFeatures")
    @WebResult(name = "getFeaturesResult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "GetFeatures", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetFeatures")
    @ResponseWrapper(localName = "GetFeaturesResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.GetFeaturesResponse")
    public GetFeaturesResult getFeatures(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language);

    /**
     * 
     * @param hotelIDs
     * @param destination
     * @param exactDestinationMatch
     * @param language
     * @param numberOfRooms
     * @param infant
     * @param checkInDate
     * @param minStarRating
     * @param password
     * @param checkOutDate
     * @param paymentMethodId
     * @param referencePointLongitude
     * @param excludeSharedFacilities
     * @param sortBy
     * @param mealIds
     * @param blockSuperdeal
     * @param maxStarRating
     * @param resortIDs
     * @param featureIds
     * @param prioritizedHotelIds
     * @param referencePointLatitude
     * @param userName
     * @param destinationID
     * @param accommodationTypes
     * @param showReviews
     * @param maxDistanceFromReferencePoint
     * @param excludeSharedRooms
     * @param numberOfChildren
     * @param totalRoomsInBatch
     * @param numberOfAdults
     * @param showCoordinates
     * @param sortOrder
     * @param minPrice
     * @param themeIds
     * @param maxPrice
     * @param currencies
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.SearchResult
     */
    @WebMethod(operationName = "Search", action = "http://xml.sunhotels.net/15/Search")
    @WebResult(name = "searchresult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "Search", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.SearchResponse")
    public SearchResult search(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "currencies", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currencies,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "numberOfRooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfRooms,
            @WebParam(name = "destination", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destination,
            @WebParam(name = "destinationID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destinationID,
            @WebParam(name = "hotelIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelIDs,
            @WebParam(name = "resortIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String resortIDs,
            @WebParam(name = "accommodationTypes", targetNamespace = "http://xml.sunhotels.net/15/")
                    String accommodationTypes,
            @WebParam(name = "numberOfAdults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfAdults,
            @WebParam(name = "numberOfChildren", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfChildren,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "sortBy", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortBy,
            @WebParam(name = "sortOrder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortOrder,
            @WebParam(name = "exactDestinationMatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String exactDestinationMatch,
            @WebParam(name = "blockSuperdeal", targetNamespace = "http://xml.sunhotels.net/15/")
                    String blockSuperdeal,
            @WebParam(name = "mealIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String mealIds,
            @WebParam(name = "showCoordinates", targetNamespace = "http://xml.sunhotels.net/15/")
                    String showCoordinates,
            @WebParam(name = "showReviews", targetNamespace = "http://xml.sunhotels.net/15/")
                    String showReviews,
            @WebParam(name = "referencePointLatitude", targetNamespace = "http://xml.sunhotels.net/15/")
                    String referencePointLatitude,
            @WebParam(name = "referencePointLongitude", targetNamespace = "http://xml.sunhotels.net/15/")
                    String referencePointLongitude,
            @WebParam(name = "maxDistanceFromReferencePoint", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxDistanceFromReferencePoint,
            @WebParam(name = "minStarRating", targetNamespace = "http://xml.sunhotels.net/15/")
                    String minStarRating,
            @WebParam(name = "maxStarRating", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxStarRating,
            @WebParam(name = "featureIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String featureIds,
            @WebParam(name = "minPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String minPrice,
            @WebParam(name = "maxPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxPrice,
            @WebParam(name = "themeIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String themeIds,
            @WebParam(name = "excludeSharedRooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    String excludeSharedRooms,
            @WebParam(name = "excludeSharedFacilities", targetNamespace = "http://xml.sunhotels.net/15/")
                    String excludeSharedFacilities,
            @WebParam(name = "prioritizedHotelIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String prioritizedHotelIds,
            @WebParam(name = "totalRoomsInBatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String totalRoomsInBatch,
            @WebParam(name = "paymentMethodId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String paymentMethodId);

    /**
     * 
     * @param hotelIDs
     * @param destination
     * @param exactDestinationMatch
     * @param language
     * @param numberOfRooms
     * @param infant
     * @param checkInDate
     * @param customerCountry
     * @param minStarRating
     * @param password
     * @param checkOutDate
     * @param paymentMethodId
     * @param referencePointLongitude
     * @param excludeSharedFacilities
     * @param sortBy
     * @param mealIds
     * @param blockSuperdeal
     * @param maxStarRating
     * @param resortIDs
     * @param featureIds
     * @param prioritizedHotelIds
     * @param referencePointLatitude
     * @param userName
     * @param destinationID
     * @param accommodationTypes
     * @param showReviews
     * @param childrenAges
     * @param maxDistanceFromReferencePoint
     * @param excludeSharedRooms
     * @param b2C
     * @param numberOfChildren
     * @param totalRoomsInBatch
     * @param numberOfAdults
     * @param showCoordinates
     * @param sortOrder
     * @param minPrice
     * @param themeIds
     * @param maxPrice
     * @param currencies
     * @return
     *     returns DAOs.SunHotelsAPIDAOs.SearchResult
     */
    @WebMethod(operationName = "SearchV2", action = "http://xml.sunhotels.net/15/SearchV2")
    @WebResult(name = "searchresult", targetNamespace = "http://xml.sunhotels.net/15/")
    @RequestWrapper(localName = "SearchV2", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.SearchV2")
    @ResponseWrapper(localName = "SearchV2Response", targetNamespace = "http://xml.sunhotels.net/15/", className = "DAOs.SunHotelsAPIDAOs.SearchV2Response")
    public SearchResult searchV2(
            @WebParam(name = "userName", targetNamespace = "http://xml.sunhotels.net/15/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://xml.sunhotels.net/15/")
                    String password,
            @WebParam(name = "language", targetNamespace = "http://xml.sunhotels.net/15/")
                    String language,
            @WebParam(name = "currencies", targetNamespace = "http://xml.sunhotels.net/15/")
                    String currencies,
            @WebParam(name = "checkInDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkInDate,
            @WebParam(name = "checkOutDate", targetNamespace = "http://xml.sunhotels.net/15/")
                    XMLGregorianCalendar checkOutDate,
            @WebParam(name = "numberOfRooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfRooms,
            @WebParam(name = "destination", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destination,
            @WebParam(name = "destinationID", targetNamespace = "http://xml.sunhotels.net/15/")
                    String destinationID,
            @WebParam(name = "hotelIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String hotelIDs,
            @WebParam(name = "resortIDs", targetNamespace = "http://xml.sunhotels.net/15/")
                    String resortIDs,
            @WebParam(name = "accommodationTypes", targetNamespace = "http://xml.sunhotels.net/15/")
                    String accommodationTypes,
            @WebParam(name = "numberOfAdults", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfAdults,
            @WebParam(name = "numberOfChildren", targetNamespace = "http://xml.sunhotels.net/15/")
                    int numberOfChildren,
            @WebParam(name = "childrenAges", targetNamespace = "http://xml.sunhotels.net/15/")
                    String childrenAges,
            @WebParam(name = "infant", targetNamespace = "http://xml.sunhotels.net/15/")
                    int infant,
            @WebParam(name = "sortBy", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortBy,
            @WebParam(name = "sortOrder", targetNamespace = "http://xml.sunhotels.net/15/")
                    String sortOrder,
            @WebParam(name = "exactDestinationMatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String exactDestinationMatch,
            @WebParam(name = "blockSuperdeal", targetNamespace = "http://xml.sunhotels.net/15/")
                    String blockSuperdeal,
            @WebParam(name = "mealIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String mealIds,
            @WebParam(name = "showCoordinates", targetNamespace = "http://xml.sunhotels.net/15/")
                    String showCoordinates,
            @WebParam(name = "showReviews", targetNamespace = "http://xml.sunhotels.net/15/")
                    String showReviews,
            @WebParam(name = "referencePointLatitude", targetNamespace = "http://xml.sunhotels.net/15/")
                    String referencePointLatitude,
            @WebParam(name = "referencePointLongitude", targetNamespace = "http://xml.sunhotels.net/15/")
                    String referencePointLongitude,
            @WebParam(name = "maxDistanceFromReferencePoint", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxDistanceFromReferencePoint,
            @WebParam(name = "minStarRating", targetNamespace = "http://xml.sunhotels.net/15/")
                    String minStarRating,
            @WebParam(name = "maxStarRating", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxStarRating,
            @WebParam(name = "featureIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String featureIds,
            @WebParam(name = "minPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String minPrice,
            @WebParam(name = "maxPrice", targetNamespace = "http://xml.sunhotels.net/15/")
                    String maxPrice,
            @WebParam(name = "themeIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String themeIds,
            @WebParam(name = "excludeSharedRooms", targetNamespace = "http://xml.sunhotels.net/15/")
                    String excludeSharedRooms,
            @WebParam(name = "excludeSharedFacilities", targetNamespace = "http://xml.sunhotels.net/15/")
                    String excludeSharedFacilities,
            @WebParam(name = "prioritizedHotelIds", targetNamespace = "http://xml.sunhotels.net/15/")
                    String prioritizedHotelIds,
            @WebParam(name = "totalRoomsInBatch", targetNamespace = "http://xml.sunhotels.net/15/")
                    String totalRoomsInBatch,
            @WebParam(name = "paymentMethodId", targetNamespace = "http://xml.sunhotels.net/15/")
                    String paymentMethodId,
            @WebParam(name = "customerCountry", targetNamespace = "http://xml.sunhotels.net/15/")
                    String customerCountry,
            @WebParam(name = "b2c", targetNamespace = "http://xml.sunhotels.net/15/")
                    String b2C);

}
